# llm/prompts/extraction/two_step.py
"""
Two-step extraction: entities first, then relationships.
Used by the Ingestor for improved extraction quality.
"""

entity_extraction_only = {
    "entity_extraction": (
        "---Goal---\n"
        "Given the conversation, identify all core entities for comprehensive knowledge-graph construction.\n"
        "Do not hallucinate facts not in the summary.\n"
        "Use English for all outputs (translate names/descriptions if the summary is not English).\n\n"


        "---Reference Time---\n"
        "Assume the dialogue took place at {dialogue_datetime}. \n"

        "---Instructions---\n"
        "• Always output in English.\n"
        "• `entity_type` must be one of: [{entity_types}].\n"
        "• Output ONLY entities (no relationships).\n"
        "• Each entity must have a concise, factual, non-empty description.\n"
        "• Use temporal anchor names exactly as written in the rewritten conversation when present; do not rename them.\n"
        "• IMPORTANT formatting rules:\n"
        "  – Output ONE entity per line (do not include newline characters inside a record).\n"
        "  – Do NOT output `{record_delimiter}` or `{completion_delimiter}` inside any field.\n"
        "  – Do NOT output `{tuple_delimiter}` inside `entity_name` or `entity_type`.\n"
        "  – If needed, replace `{tuple_delimiter}` with a normal hyphen '-' inside descriptions.\n\n"


        "---Event & Temporal Anchor Modeling---\n"
        "• Create Event entities for important actions, plans, meetings, trips, decisions, changes, milestones, or incidents.\n"
        "• Event names must be semantic action/object names, not dates, timespans, times, or relative phrases.\n"
        "• Marker tags are authoritative temporal anchors: `[DATE: ...]`, `[TIME: ...]`, `[TIMESPAN: ...]`.\n"
        "• For every marker tag, extract one matching temporal entity:\n"
        "  – `[DATE: X]` → Date entity with entity_name = X.\n"
        "  – `[TIME: X]` → Time entity with entity_name = X.\n"
        "  – `[TIMESPAN: X]` → Timespan entity with entity_name = X.\n"
        "• Do not compute, rename, normalize, or paraphrase marker payloads.\n"
        "• Never replace an Event with a temporal entity. If an event and marker appear together, output BOTH.\n"
        "• Temporal entity descriptions should describe only the time anchor; event details belong in Event descriptions or relations.\n"
        "• Fuzzy time without a marker stays unresolved; do not invent exact dates.\n\n"


        "---Core Entity Definition---\n"
        "Core entities are specific, distinguishable subjects that are central to the dialogue or important for future recall, including:\n"
        "• Named people, pets/animals, places, organizations, products, tools, systems, projects, or personal possessions.\n"
        "• Important items, documents, devices, artifacts, or transaction objects.\n"
        "• Central events, plans, trips, experiments, problems, incidents, decisions, or cases.\n"
        "• Long-lived user goals, tasks, preferences, constraints, habits, or states.\n\n"
        "Prefer specific named entities over generic paraphrases.\n"
        "Exclude:\n"
        "• Minor examples or isolated list items.\n"
        "• Pure attributes/values/adjectives as standalone entities.\n\n"

        "---Steps---\n"
        "1) Identify core entities (including Person, any key Event, Date/Time/Timespan, Location anchors).\n"
        "2) For each entity, output exactly ONE line with this exact format:\n"
        "(\"entity\"{tuple_delimiter}<entity_name>{tuple_delimiter}<entity_type>{tuple_delimiter}<entity_description>)\n\n"
        "   • For `[DATE: ...]`, output a Date entity whose entity_name is the marker payload exactly as written.\n"
        "   • For `[TIME: ...]`, output a Time entity whose entity_name is the marker payload exactly as written.\n"
        "   • For `[TIMESPAN: ...]`, output a Timespan entity whose entity_name is the marker payload exactly as written.\n"
        "   • For unmarked absolute dates/timespans/times, use the explicit normalized value stated in the conversation.\n"
        "3) Return the result as a single flat list of entity lines separated by {record_delimiter}, "
        "and finish with {completion_delimiter}.\n\n"

        "---Examples---\n"
        "Example 1 (tech/tool conversation):\n"
        "Reference time: 2024-03-10 09:00\n"
        "Conversation:\n"
        "User: I'm building a memory-based chat system using LangChain with FAISS and HuggingFaceEmbeddings.\n"
        "Assistant: That sounds great! FAISS is very efficient for similarity search.\n"
        "Output:\n"
        "(\"entity\"{tuple_delimiter}User{tuple_delimiter}Person{tuple_delimiter}The user building the chat system.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}LangChain{tuple_delimiter}Product{tuple_delimiter}A framework used to build LLM applications.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}FAISS{tuple_delimiter}Product{tuple_delimiter}A vector database used for similarity search.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}HuggingFaceEmbeddings{tuple_delimiter}Product{tuple_delimiter}An embedding component used to generate vector representations.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}Memory-based chat system{tuple_delimiter}Product{tuple_delimiter}A chat system that retrieves past context using stored embeddings.)"
        "{completion_delimiter}\n\n"
        "Example 2 (personal conversation between two named people):\n"
        "Reference time: 2023-05-25 13:14\n"
        "Conversation:\n"
        "Melanie: Hey Caroline, I ran a charity race for mental health last Saturday — it was really rewarding.\n"
        "Caroline: That's amazing! I've been researching adoption agencies — it's been a dream to give a loving home to kids who need it.\n"
        "Melanie: My kids are excited about summer break; we're thinking of going camping next month.\n"
        "Output:\n"
        "(\"entity\"{tuple_delimiter}Melanie{tuple_delimiter}Person{tuple_delimiter}One of the two speakers; a mother raising awareness for mental health.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}Caroline{tuple_delimiter}Person{tuple_delimiter}One of the two speakers; exploring adoption to start a family.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}Charity race for mental health{tuple_delimiter}Event{tuple_delimiter}A charity race Melanie ran to raise awareness for mental health.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}2023-05-20{tuple_delimiter}Date{tuple_delimiter}Resolved date of the charity race — 'last Saturday' before the reference date 2023-05-25.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}Adoption agency research{tuple_delimiter}Event{tuple_delimiter}Caroline's ongoing research into adoption agencies to build a family.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}Family camping trip{tuple_delimiter}Event{tuple_delimiter}A camping trip Melanie's family is planning for next month.){record_delimiter}"
        "(\"entity\"{tuple_delimiter}2023-06{tuple_delimiter}Date{tuple_delimiter}Approximate month of the planned camping trip — 'next month' from 2023-05-25.)"
        "{completion_delimiter}\n\n"

        "######################\n---Real Data---\n######################\n"
        "Raw conversation:\n"
        "{raw_conversation}\n"
        "######################\n"
        "Output:"
    )
}

relationship_extraction_only = {
    "relationship_extraction": (
        "---Goal---\n"
        "Given the conversation and the provided entity list, identify relationships among these entities for knowledge-graph construction.\n"
        "Do not hallucinate facts not in the summary.\n"
        "Use English for all outputs.\n\n"

        "---Reference Time---\n"
        "Assume the dialogue took place at {dialogue_datetime}. \n"
        "BUT do not create new Date/Time entities; use only the provided entities.\n\n"

        "---Instructions---\n"
        "• Always output in English.\n"
        "• Output ONLY relationships (no entities).\n"
        "• `relationship_keywords`: 2–4 lowercase English words, comma-separated (letters and commas only).\n"
        "• `source_entity` and `target_entity` must exactly match an `entity_name` from the provided entity list.\n"
        "• Use provided entity names exactly as written, including resolved temporal names when present.\n"
        "• Do not invent entities. If a needed entity is missing, omit that relationship.\n"
        "• Do not recompute, rename, or paraphrase temporal anchors in relationships.\n"
        "• One relationship record per line; do not include newline characters inside a record.\n"
        "• Do NOT output `{record_delimiter}` or `{completion_delimiter}` inside any field.\n"
        "• Do NOT output `{tuple_delimiter}` inside `source_entity` or `target_entity`.\n\n"

        "---Relationship Guidelines---\n"
        "• Prefer WHEN/WHERE links:\n"
        "  – Event → Date/Time/Timespan (WHEN)\n"
        "  – Event → Location (WHERE)\n"
        "• Use edges that help answer WHEN/WHERE/WHAT/WHO/HOW questions.\n"
        "• Recommended keywords (pick those that fit):\n"
        "  needs_to_pick_up, needs_to_return, exchanged_for, purchased_on, occurs_on, occurs_at, planned_for, located_in, met_at,\n"
        "  related_to, discusses, decides, requests, resolves.\n\n"

        "---Output Format---\n"
        "Output each relationship with this exact format:\n"
        "(\"relationship\"{tuple_delimiter}<source_entity>{tuple_delimiter}<target_entity>{tuple_delimiter}<relationship_description>{tuple_delimiter}<relationship_keywords>)\n\n"
        "Return the result as a single flat list of relationship lines separated by {record_delimiter}, "
        "and finish with {completion_delimiter}.\n\n"

        "---Examples---\n"
        "Example 1 (user/assistant, scheduling):\n"
        "Reference time: 2025-08-20 16:00\n"
        "Conversation:\n"
        "User: I scheduled a dental checkup for tomorrow at 10:30 at City Dental Clinic. I also need to call them today to confirm.\n"
        "Provided Entities:\n"
        "- User (Person): The user in the dialogue.\n"
        "- Dental checkup appointment (Event): A planned dental visit.\n"
        "- 2025-08-21 (Date): Date resolved from 'tomorrow'.\n"
        "- 10:30 (Time): Appointment time.\n"
        "- City Dental Clinic (Organization): The clinic providing the service.\n"
        "- Phone confirmation call (Event): A planned call to confirm the appointment.\n"
        "- 2025-08-20 (Date): Reference date (today).\n"
        "Output:\n"
        "(\"relationship\"{tuple_delimiter}Dental checkup appointment{tuple_delimiter}2025-08-21{tuple_delimiter}appointment occurs on the resolved date from 'tomorrow'{tuple_delimiter}occurs_on){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Dental checkup appointment{tuple_delimiter}10:30{tuple_delimiter}appointment scheduled at this time{tuple_delimiter}occurs_at){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Dental checkup appointment{tuple_delimiter}City Dental Clinic{tuple_delimiter}appointment takes place at the clinic{tuple_delimiter}located_in){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Phone confirmation call{tuple_delimiter}2025-08-20{tuple_delimiter}call planned for the reference date (today){tuple_delimiter}planned_for){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Phone confirmation call{tuple_delimiter}City Dental Clinic{tuple_delimiter}call is made to the clinic{tuple_delimiter}related_to)"
        "{completion_delimiter}\n\n"
        "Example 2 (personal conversation between two named people):\n"
        "Reference time: 2023-05-25 13:14\n"
        "Conversation:\n"
        "Melanie: Hey Caroline, I ran a charity race for mental health last Saturday — really rewarding.\n"
        "Caroline: That's amazing! I've been researching adoption agencies — it's been a dream to give a loving home to kids who need it.\n"
        "Melanie: My kids are excited about summer break; we're thinking of going camping next month.\n"
        "Provided Entities:\n"
        "- Melanie (Person): One of the two speakers; a mother raising awareness for mental health.\n"
        "- Caroline (Person): One of the two speakers; exploring adoption to start a family.\n"
        "- Charity race for mental health (Event): A charity race Melanie ran to raise awareness for mental health.\n"
        "- 2023-05-20 (Date): Resolved date of the charity race — 'last Saturday' before 2023-05-25.\n"
        "- Adoption agency research (Event): Caroline's ongoing research into adoption agencies.\n"
        "- Family camping trip (Event): A camping trip Melanie's family is planning for next month.\n"
        "- 2023-06 (Date): Approximate month of the planned camping trip.\n"
        "Output:\n"
        "(\"relationship\"{tuple_delimiter}Melanie{tuple_delimiter}Charity race for mental health{tuple_delimiter}Melanie participated in the charity race{tuple_delimiter}participates_in){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Charity race for mental health{tuple_delimiter}2023-05-20{tuple_delimiter}charity race occurred on this resolved date{tuple_delimiter}occurs_on){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Caroline{tuple_delimiter}Adoption agency research{tuple_delimiter}Caroline is conducting the research{tuple_delimiter}conducts){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Melanie{tuple_delimiter}Family camping trip{tuple_delimiter}Melanie is planning the trip with her family{tuple_delimiter}plans){record_delimiter}"
        "(\"relationship\"{tuple_delimiter}Family camping trip{tuple_delimiter}2023-06{tuple_delimiter}camping trip is planned for this month{tuple_delimiter}planned_for)"
        "{completion_delimiter}\n\n"

        "######################\n---Real Data---\n######################\n"
        "Raw conversation:\n"
        "{raw_conversation}\n\n"
        "Provided Entities (ONLY use these entity_name values; do not add new entities):\n"
        "{entities_text}\n"
        "######################\n"
        "Output:"
    )
}
